### ISSUE TITLE
Configure handle size via CSS

### ISSUE THREAD

**Issue by IlyaSemenov** [gausszhou/vue3-drag-resize-rotate#37]
Currently, the handle size is configured via `style` attributes and manual pixel value calculations:

https://github.com/gausszhou/vue3-drag-resize-rotate/blob/5b17bb43c09f64914a8f590ff20cccf6983087da/src/components/vue-drag-resize-rotate/index.vue#L351-L354

That makes it very inconvenient to override it with CSS. For instance, I wanted the handle to increase slightly on hover, but that's not directly possible as you're not only hardcoding fixed `width` in a style but also use it to calculate fixed pixel offsets (see above).

I propose to get rid of `handleInfo` completely, and use CSS for handle size, and replace hardcoded values inside `calc` with `translate` for centering:

```scss
.handle {
  width: 8px;
  height: 8px;
  &-tl {
    top: 0;
    left: 0;
    transform: translate(-50%, -50%);
  }
  &-tr {
    top: 0;
    right: 0;
    transform: translate(50%, -50%);
  }
  &-bl {
    bottom: 0;
    left: 0;
    transform: translate(-50%, 50%);
  }
  &-br {
    bottom: 0;
    right: 0;
    transform: translate(50%, 50%);
  }
  &-rot {
    top: 0;
    left: 50%;
    transform: translate(-50%, -50%);
  }
}
```

This is what I actually ended up doing, passing `:handle-info="{ size: 0, offset: 0, switch: true }"` to get rid of the hardcoded offsets. My point is that's how the library should work in the first place.
